repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        name: ⚙️ Check YAML
      - id: check-toml
        name: ⚙️ Check TOML
      - id: end-of-file-fixer
        name: ⚙️ End of file fixer
      - id: trailing-whitespace
        name: ⚙️ Trailing whitespace remover
      - id: check-case-conflict
        name: ⚙️ Check case conflict
      - id: check-docstring-first
        name: ⚙️ Check docstring first
      - id: check-merge-conflict
        name: ⚙️ Check merge conflict
      - id: detect-private-key
        name: ⚙️ Detect private key
      - id: debug-statements
        name: "⚙️ Check debug statements"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        name: 🆎 Static type checking using mypy
        language: python
        exclude: ^tests/
        additional_dependencies:
          - types-redis
          - types-requests

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.1
    hooks:
      - id: ruff
        name: 🧹 Lint code with Ruff
        language: python
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: 🧹 Format code with Ruff

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: 🖌️ Format code with Prettier
        files: \.(json|markdown|md|yaml|yml)$
        args: [--write]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint
        name: 🐳 Lint Dockerfiles
