version: "3"
services:
  bot:
    image: ghcr.io/adrianvillanueva997/telegrambot_transcriber:latest
    container_name: telegrambot_transcriber
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8000
