services:
  bot:
    image: ghcr.io/adrianvillanueva997/telegrambot_transcriber:v2.0.0
    container_name: telegrambot_transcriber
    restart: unless-stopped
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
