version: '3'
services:
  bot:
    image: ghcr.io/adrianvillanueva997/telegrambot_transcriber:latest
    container_name: telegrambot_transcriber
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    networks:
      - bots
networks:
  bots:
    external: true