services:
  bot:
    image: ghcr.io/adrianvillanueva997/telegrambot_transcriber:v2.0.6
    container_name: telegrambot_transcriber
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
