name: telegrambot_transcriber
services:
  web:
    image: ghcr.io/adrianvillanueva997/telegrambot_transcriber:v1.0.0
    networks:
      - proxy
    container_name: telegrambot_transcriber
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.transcriber-redirect-websecure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.transcriber-redirect-websecure.redirectscheme.permanent=true"
      - "traefik.http.routers.transcriber-web.middlewares=transcriber-redirect-websecure"
      - traefik.http.routers.transcriber-web.rule=Host(`transcriber.thexiao77.com`)
      - traefik.http.routers.transcriber-web.entrypoints=http
      - traefik.http.routers.transcriber-websecure.rule=Host(`transcriber.thexiao77.com`)
      - traefik.http.routers.transcriber-websecure.tls.certresolver=le
      - traefik.http.routers.transcriber-websecure.tls=true
      - traefik.http.routers.transcriber-websecure.entrypoints=https
      - "traefik.docker.network=proxy"
    env_file: stack.env
    ports:
      - 8000