[tool.poetry]
name = "transcriber_telegrambot"
version = "0.1.0"
description = ""
authors = ["adrianvillanueva997 <adrianvillanueva997@gmail.com>"]

[tool.poetry.dependencies]
python = ">= 3.10 <4"
asyncio = "^3.4.3"
python-telegram-bot = "^20.0"
pydub = "^0.25.1"
ffmpeg-python = "^0.2.0"
vosk = "^0.3.45"
prometheus-client = "^0.15.0"
loguru = "^0.6.0"


[tool.poetry.dev-dependencies]
black = "^22.12.0"
isort = "^5.11.4"
mypy = "^0.991"
pytest = "^7.2.0"
pylama = "^8.4.1"
bandit = "^1.7.4"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
